---
- name: Ensure ca-certificates are installed
  yum:
    name: ca-certificates
    state: present
  become: yes

- name: Create /etc/yum.repos.d directory if it does not exist
  file:
    path: /etc/yum.repos.d
    state: directory
    mode: "0755"
  become: yes

- name: Clean yum cache
  yum:
    name: "*"
    state: latest
    update_cache: yes
  become: yes

- name: Add Grafana YUM repository
  yum_repository:
    name: grafana
    description: "Grafana OSS YUM Repository"
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: yes
    gpgkey: https://packages.grafana.com/gpg.key
    enabled: yes
  become: yes

- name: Try installing Grafana via YUM
  yum:
    name: grafana
    state: latest
  become: yes
  ignore_errors: yes

# Fallback to RPM installation if YUM repository doesn't work
- name: Download Grafana RPM package
  get_url:
    url: https://dl.grafana.com/oss/release/grafana-9.5.1-1.x86_64.rpm
    dest: /tmp/grafana.rpm
  when: ansible_facts.pkg_mgr == "yum"
  become: yes

- name: Install Grafana from RPM
  yum:
    name: /tmp/grafana.rpm
    state: present
  become: yes
  when: ansible_facts.pkg_mgr == "yum"

- name: Ensure Grafana is running and enabled
  systemd:
    name: grafana-server
    state: started
    enabled: yes
  become: yes

- name: Wait for Grafana to be up and running
  wait_for:
    port: 3000
    timeout: 60

- name: Pause for 10 seconds to allow Grafana to fully initialize
  pause:
    seconds: 10

- name: Test Grafana API
  uri:
    url: "http://localhost:3000/api/health"
    method: GET
  register: grafana_health
  retries: 3
  delay: 5
  until: grafana_health.status == 200

- name: Display Grafana health check result
  debug:
    var: grafana_health

- name: Display Grafana version from health check
  debug:
    msg: "Grafana version {{ grafana_health.json.version }} is installed"
  when: grafana_health.status == 200
