- name: Test Grafana API
  uri:
    url: "http://localhost:3000/api/health"
    method: GET
  register: grafana_health

- name: Display Grafana health check result
  debug:
    var: grafana_health

- name: Display Grafana version from health check
  debug:
    msg: "Grafana version {{ grafana_health.json.version }} is installed"

- name: Check for Grafana updates
  apt:
    name: grafana
    state: latest
    update_cache: yes
  check_mode: yes
  register: grafana_update_check
  become: yes

- name: Display update status
  debug:
    msg: "Grafana update is {{ 'available' if grafana_update_check.changed else 'not available' }}"

- name: Confirm Grafana API is accessible
  debug:
    msg: "Grafana API is accessible and functioning correctly"
  when: grafana_health.status == 200

- name: Ensure Grafana is running and enabled
  systemd:
    name: grafana-server
    state: started
    enabled: yes
  become: yes

- name: Check if Grafana is listening on port 3000
  wait_for:
    port: 3000
    timeout: 60

- name: Verify Grafana is running and listening
  debug:
    msg: "Grafana is running and listening on port 3000"
