- name: Check Grafana version
  command: grafana-server -v
  register: grafana_version
  changed_when: false
  become: yes

- name: Display Grafana version
  debug:
    var: grafana_version.stdout_lines[0]

- name: Check Grafana service status
  service:
    name: grafana-server
    state: started
  register: grafana_service
  become: yes

- name: Display Grafana service status
  debug:
    var: grafana_service

- name: Test Grafana API
  uri:
    url: "http://localhost:3000/api/health"
    method: GET
  register: grafana_health

- name: Display Grafana health check result
  debug:
    var: grafana_health

- name: Fail if Grafana API is not accessible
  fail:
    msg: "Grafana API is not accessible"
  when: grafana_health.status != 200
