---
- name: Ensure ca-certificates are installed and updated
  apt:
    name: ca-certificates
    state: latest
    update_cache: yes
  become: yes

- name: Clean apt cache
  apt:
    autoclean: yes
  become: yes

- name: Download Grafana GPG key manually using curl
  command: curl -fsSL https://packages.grafana.com/gpg.key -o /tmp/grafana.gpg.key
  become: yes

- name: Add Grafana GPG key from file
  apt_key:
    file: /tmp/grafana.gpg.key
    state: present
  become: yes

- name: Add Grafana APT repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    filename: "grafana"
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install Grafana on Ubuntu
  apt:
    name: grafana
    state: present
  become: yes

- name: Ensure Grafana is running and enabled
  systemd:
    name: grafana-server
    state: started
    enabled: yes
  become: yes

- name: Wait for Grafana to be up and running
  wait_for:
    port: 3000
    timeout: 60

- name: Pause for 10 seconds to allow Grafana to fully initialize
  pause:
    seconds: 10

- name: Test Grafana API
  uri:
    url: "http://localhost:3000/api/health"
    method: GET
  register: grafana_health
  retries: 3
  delay: 5
  until: grafana_health.status == 200

- name: Display Grafana health check result
  debug:
    var: grafana_health

- name: Display Grafana version from health check
  debug:
    msg: "Grafana version {{ grafana_health.json.version }} is installed"
  when: grafana_health.status == 200

- name: Check for Grafana updates
  apt:
    name: grafana
    state: latest
    update_cache: yes
  check_mode: yes
  register: grafana_update_check
  become: yes

- name: Display update status
  debug:
    msg: "Grafana update is {{ 'available' if grafana_update_check.changed else 'not available' }}"

- name: Confirm Grafana API is accessible
  debug:
    msg: "Grafana API is accessible and functioning correctly"
  when: grafana_health.status == 200
