name: Ansible Test and Auto Merge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_playbooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu, amazon_linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible==2.9.20 jinja2==2.11.3 markupsafe==2.0.1

      - name: Run Ansible Playbook (Grafana)
        run: ansible-playbook playbooks/install_grafana.yml -i inventories/staging/hosts.yml --extra-vars "ansible_distribution=${{ matrix.os }}"

      - name: Run Ansible Playbook (Prometheus)
        run: ansible-playbook playbooks/install_prometheus.yml -i inventories/staging/hosts.yml --extra-vars "ansible_distribution=${{ matrix.os }}"

      - name: Run Ansible Playbook (Netdata)
        run: ansible-playbook playbooks/install_prometheus.yml -i inventories/staging/hosts.yml --extra-vars "ansible_distribution=${{ matrix.os }}"

        env:
          GRAFANA_VERSION: "9.5.1"
